[project]
name = "shopee-recommendation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx[http2]>=0.28.1",
    "playwright-stealth>=2.0.0",
    "playwright>=1.57.0",
]
